# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pageDaftar.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../TugasAkhir_Prolan/PageLogin/P_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.widget.setMinimumSize(QtCore.QSize(500, 500))
        self.widget.setMaximumSize(QtCore.QSize(500, 500))
        self.widget.setObjectName("widget")
        self.Frame = QtWidgets.QLabel(self.widget)
        self.Frame.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.Frame.setMinimumSize(QtCore.QSize(500, 500))
        self.Frame.setMaximumSize(QtCore.QSize(500, 500))
        self.Frame.setText("")
        self.Frame.setPixmap(QtGui.QPixmap("../mainApplication/Picture/FrameDaftar.jpg"))
        self.Frame.setScaledContents(True)
        self.Frame.setObjectName("Frame")
        self.inputNama = QtWidgets.QLineEdit(self.widget)
        self.inputNama.setGeometry(QtCore.QRect(154, 180, 189, 22))
        self.inputNama.setMinimumSize(QtCore.QSize(189, 22))
        self.inputNama.setMaximumSize(QtCore.QSize(189, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputNama.setFont(font)
        self.inputNama.setAcceptDrops(True)
        self.inputNama.setInputMask("")
        self.inputNama.setMaxLength(20)
        self.inputNama.setFrame(False)
        self.inputNama.setAlignment(QtCore.Qt.AlignCenter)
        self.inputNama.setPlaceholderText("")
        self.inputNama.setClearButtonEnabled(False)
        self.inputNama.setObjectName("inputNama")
        self.inputPassword = QtWidgets.QLineEdit(self.widget)
        self.inputPassword.setGeometry(QtCore.QRect(154, 232, 189, 22))
        self.inputPassword.setMinimumSize(QtCore.QSize(189, 22))
        self.inputPassword.setMaximumSize(QtCore.QSize(189, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputPassword.setFont(font)
        self.inputPassword.setAcceptDrops(True)
        self.inputPassword.setInputMask("")
        self.inputPassword.setMaxLength(15)
        self.inputPassword.setFrame(False)
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.inputPassword.setPlaceholderText("")
        self.inputPassword.setClearButtonEnabled(False)
        self.inputPassword.setObjectName("inputPassword")
        self.inputRePassword = QtWidgets.QLineEdit(self.widget)
        self.inputRePassword.setGeometry(QtCore.QRect(154, 288, 189, 22))
        self.inputRePassword.setMinimumSize(QtCore.QSize(189, 22))
        self.inputRePassword.setMaximumSize(QtCore.QSize(189, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputRePassword.setFont(font)
        self.inputRePassword.setAcceptDrops(True)
        self.inputRePassword.setInputMask("")
        self.inputRePassword.setMaxLength(15)
        self.inputRePassword.setFrame(False)
        self.inputRePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputRePassword.setAlignment(QtCore.Qt.AlignCenter)
        self.inputRePassword.setPlaceholderText("")
        self.inputRePassword.setClearButtonEnabled(False)
        self.inputRePassword.setObjectName("inputRePassword")
        self.buttonDaftar = QtWidgets.QToolButton(self.widget)
        self.buttonDaftar.setGeometry(QtCore.QRect(217, 327, 69, 29))
        self.buttonDaftar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonDaftar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../mainApplication/Picture/buttonDaftar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDaftar.setIcon(icon1)
        self.buttonDaftar.setIconSize(QtCore.QSize(65, 23))
        self.buttonDaftar.setAutoRaise(True)
        self.buttonDaftar.setObjectName("buttonDaftar")
        self.notice = QtWidgets.QLabel(self.widget)
        self.notice.setGeometry(QtCore.QRect(160, 365, 181, 35))
        self.notice.setMinimumSize(QtCore.QSize(181, 35))
        self.notice.setMaximumSize(QtCore.QSize(181, 35))
        self.notice.setText("")
        self.notice.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.notice.setObjectName("notice")
        self.iconHide = QtWidgets.QToolButton(self.widget)
        self.iconHide.setGeometry(QtCore.QRect(310, 234, 29, 18))
        self.iconHide.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iconHide.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../mainApplication/Picture/iconHideEcho.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconHide.setIcon(icon2)
        self.iconHide.setIconSize(QtCore.QSize(29, 22))
        self.iconHide.setAutoRaise(True)
        self.iconHide.setObjectName("iconHide")
        self.iconHide_2 = QtWidgets.QToolButton(self.widget)
        self.iconHide_2.setGeometry(QtCore.QRect(310, 290, 29, 18))
        self.iconHide_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iconHide_2.setText("")
        self.iconHide_2.setIcon(icon2)
        self.iconHide_2.setIconSize(QtCore.QSize(29, 22))
        self.iconHide_2.setAutoRaise(True)
        self.iconHide_2.setObjectName("iconHide_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APLIKASI COBAAN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
