from PyQt5 import QtCore, QtGui, QtWidgets

def pageOperasiTerjual(self) :
    self.pageOperasiTerjual = dict()
    self.pageOperasiTerjual["widget"] = QtWidgets.QWidget(self.centralwidget)
    self.pageOperasiTerjual["widget"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageOperasiTerjual["widget"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageOperasiTerjual["widget"].setMaximumSize(QtCore.QSize(500, 500))

    self.pageOperasiTerjual["Frame"] = QtWidgets.QLabel(self.pageOperasiTerjual["widget"])
    self.pageOperasiTerjual["Frame"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageOperasiTerjual["Frame"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageOperasiTerjual["Frame"].setMaximumSize(QtCore.QSize(500, 500))
    self.pageOperasiTerjual["Frame"].setText("")
    self.pageOperasiTerjual["Frame"].setPixmap(QtGui.QPixmap("Picture/FrameDataTerjual.jpg"))
    self.pageOperasiTerjual["Frame"].setScaledContents(True)

    self.pageOperasiTerjual["buttonView"] = QtWidgets.QToolButton(self.pageOperasiTerjual["widget"])
    self.pageOperasiTerjual["buttonView"].setGeometry(QtCore.QRect(160, 199, 180, 32))
    self.pageOperasiTerjual["buttonView"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageOperasiTerjual["buttonView"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonViewData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageOperasiTerjual["buttonView"].setIcon(icon)
    self.pageOperasiTerjual["buttonView"].setIconSize(QtCore.QSize(174, 28))
    self.pageOperasiTerjual["buttonView"].setAutoRaise(True)

    self.pageOperasiTerjual["buttonInput"] = QtWidgets.QToolButton(self.pageOperasiTerjual["widget"])
    self.pageOperasiTerjual["buttonInput"].setGeometry(QtCore.QRect(160, 261, 181, 31))
    self.pageOperasiTerjual["buttonInput"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageOperasiTerjual["buttonInput"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonInputData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageOperasiTerjual["buttonInput"].setIcon(icon)
    self.pageOperasiTerjual["buttonInput"].setIconSize(QtCore.QSize(175, 33))
    self.pageOperasiTerjual["buttonInput"].setAutoRaise(True)

    self.pageOperasiTerjual["buttonDelete"] = QtWidgets.QToolButton(self.pageOperasiTerjual["widget"])
    self.pageOperasiTerjual["buttonDelete"].setGeometry(QtCore.QRect(160, 320, 180, 32))
    self.pageOperasiTerjual["buttonDelete"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageOperasiTerjual["buttonDelete"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonDeleteData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageOperasiTerjual["buttonDelete"].setIcon(icon)
    self.pageOperasiTerjual["buttonDelete"].setIconSize(QtCore.QSize(174, 28))
    self.pageOperasiTerjual["buttonDelete"].setAutoRaise(True)

    self.pageOperasiTerjual["buttonBack"] = QtWidgets.QToolButton(self.pageOperasiTerjual["widget"])
    self.pageOperasiTerjual["buttonBack"].setGeometry(QtCore.QRect(200, 367, 101, 36))
    self.pageOperasiTerjual["buttonBack"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageOperasiTerjual["buttonBack"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonBack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageOperasiTerjual["buttonBack"].setIcon(icon)
    self.pageOperasiTerjual["buttonBack"].setIconSize(QtCore.QSize(100, 39))
    self.pageOperasiTerjual["buttonBack"].setAutoRaise(True)

