from PyQt5 import QtCore, QtGui, QtWidgets

def pageDaftar(self):
    self.pageDaftar = dict()
    self.pageDaftar["widget"] = QtWidgets.QWidget(self.centralwidget)
    self.pageDaftar["widget"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageDaftar["widget"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageDaftar["widget"].setMaximumSize(QtCore.QSize(500, 500))

    self.pageDaftar["Frame"] = QtWidgets.QLabel(self.pageDaftar["widget"])
    self.pageDaftar["Frame"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageDaftar["Frame"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageDaftar["Frame"].setMaximumSize(QtCore.QSize(500, 500))
    self.pageDaftar["Frame"].setText("")
    self.pageDaftar["Frame"].setPixmap(QtGui.QPixmap("Picture/FrameDaftar.jpg"))
    self.pageDaftar["Frame"].setScaledContents(True)

    self.pageDaftar["inputNama"] = QtWidgets.QLineEdit(self.pageDaftar["widget"])
    self.pageDaftar["inputNama"].setGeometry(QtCore.QRect(154, 180, 189, 22))
    self.pageDaftar["inputNama"].setMinimumSize(QtCore.QSize(189, 22))
    self.pageDaftar["inputNama"].setMaximumSize(QtCore.QSize(189, 22))
    font = QtGui.QFont()
    font.setPointSize(10)
    self.pageDaftar["inputNama"].setFont(font)
    self.pageDaftar["inputNama"].setAcceptDrops(True)
    self.pageDaftar["inputNama"].setInputMask("")
    self.pageDaftar["inputNama"].setMaxLength(15)
    self.pageDaftar["inputNama"].setFrame(False)
    self.pageDaftar["inputNama"].setAlignment(QtCore.Qt.AlignCenter)
    self.pageDaftar["inputNama"].setPlaceholderText("")
    self.pageDaftar["inputNama"].setClearButtonEnabled(False)

    self.pageDaftar["inputPassword"] = QtWidgets.QLineEdit(self.pageDaftar["widget"])
    self.pageDaftar["inputPassword"].setGeometry(QtCore.QRect(154, 232, 189, 22))
    self.pageDaftar["inputPassword"].setMinimumSize(QtCore.QSize(189, 22))
    self.pageDaftar["inputPassword"].setMaximumSize(QtCore.QSize(189, 22))
    font = QtGui.QFont()
    font.setPointSize(10)
    self.pageDaftar["inputPassword"].setFont(font)
    self.pageDaftar["inputPassword"].setAcceptDrops(True)
    self.pageDaftar["inputPassword"].setInputMask("")
    self.pageDaftar["inputPassword"].setMaxLength(15)
    self.pageDaftar["inputPassword"].setFrame(False)
    self.pageDaftar["inputPassword"].setEchoMode(QtWidgets.QLineEdit.Password)
    self.pageDaftar["inputPassword"].setAlignment(QtCore.Qt.AlignCenter)
    self.pageDaftar["inputPassword"].setPlaceholderText("")
    self.pageDaftar["inputPassword"].setClearButtonEnabled(False)

    self.pageDaftar["inputRePassword"] = QtWidgets.QLineEdit(self.pageDaftar["widget"])
    self.pageDaftar["inputRePassword"].setGeometry(QtCore.QRect(154, 288, 189, 22))
    self.pageDaftar["inputRePassword"].setMinimumSize(QtCore.QSize(189, 22))
    self.pageDaftar["inputRePassword"].setMaximumSize(QtCore.QSize(189, 22))
    font = QtGui.QFont()
    font.setPointSize(10)
    self.pageDaftar["inputRePassword"].setFont(font)
    self.pageDaftar["inputRePassword"].setAcceptDrops(True)
    self.pageDaftar["inputRePassword"].setInputMask("")
    self.pageDaftar["inputRePassword"].setMaxLength(30)
    self.pageDaftar["inputRePassword"].setFrame(False)
    self.pageDaftar["inputRePassword"].setEchoMode(QtWidgets.QLineEdit.Password)
    self.pageDaftar["inputRePassword"].setAlignment(QtCore.Qt.AlignCenter)
    self.pageDaftar["inputRePassword"].setPlaceholderText("")
    self.pageDaftar["inputRePassword"].setClearButtonEnabled(False)

    self.pageDaftar["buttonDaftar"] = QtWidgets.QToolButton(self.pageDaftar["widget"])
    self.pageDaftar["buttonDaftar"].setGeometry(QtCore.QRect(217, 327, 69, 29))
    self.pageDaftar["buttonDaftar"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageDaftar["buttonDaftar"].setText("")
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap("Picture/buttonDaftar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageDaftar["buttonDaftar"].setIcon(icon1)
    self.pageDaftar["buttonDaftar"].setIconSize(QtCore.QSize(65, 23))
    self.pageDaftar["buttonDaftar"].setAutoRaise(True)

    self.pageDaftar["notice"] = QtWidgets.QLabel(self.pageDaftar["widget"])
    self.pageDaftar["notice"].setGeometry(QtCore.QRect(160, 365, 181, 35))
    self.pageDaftar["notice"].setMinimumSize(QtCore.QSize(181, 35))
    self.pageDaftar["notice"].setMaximumSize(QtCore.QSize(181, 35))
    self.pageDaftar["notice"].setText("")
    self.pageDaftar["notice"].setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)

