from PyQt5 import QtCore, QtGui, QtWidgets

def pageOperasiPenjualan(self) :
    self.pageOperasiPenjualan = dict()
    self.pageOperasiPenjualan["widget"] = QtWidgets.QWidget(self.centralwidget)
    self.pageOperasiPenjualan["widget"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageOperasiPenjualan["widget"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageOperasiPenjualan["widget"].setMaximumSize(QtCore.QSize(500, 500))

    self.pageOperasiPenjualan["Frame"] = QtWidgets.QLabel(self.pageOperasiPenjualan["widget"])
    self.pageOperasiPenjualan["Frame"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageOperasiPenjualan["Frame"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageOperasiPenjualan["Frame"].setMaximumSize(QtCore.QSize(500, 500))
    self.pageOperasiPenjualan["Frame"].setText("")
    self.pageOperasiPenjualan["Frame"].setPixmap(QtGui.QPixmap("Picture/FrameDataPenjualan.jpg"))
    self.pageOperasiPenjualan["Frame"].setScaledContents(True)

    self.pageOperasiPenjualan["buttonView"] = QtWidgets.QToolButton(self.pageOperasiPenjualan["widget"])
    self.pageOperasiPenjualan["buttonView"].setGeometry(QtCore.QRect(160, 199, 180, 32))
    self.pageOperasiPenjualan["buttonView"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageOperasiPenjualan["buttonView"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonViewData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageOperasiPenjualan["buttonView"].setIcon(icon)
    self.pageOperasiPenjualan["buttonView"].setIconSize(QtCore.QSize(174, 28))
    self.pageOperasiPenjualan["buttonView"].setAutoRaise(True)

    self.pageOperasiPenjualan["buttonInput"] = QtWidgets.QToolButton(self.pageOperasiPenjualan["widget"])
    self.pageOperasiPenjualan["buttonInput"].setGeometry(QtCore.QRect(160, 261, 181, 31))
    self.pageOperasiPenjualan["buttonInput"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageOperasiPenjualan["buttonInput"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonInputData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageOperasiPenjualan["buttonInput"].setIcon(icon)
    self.pageOperasiPenjualan["buttonInput"].setIconSize(QtCore.QSize(175, 33))
    self.pageOperasiPenjualan["buttonInput"].setAutoRaise(True)

    self.pageOperasiPenjualan["buttonDelete"] = QtWidgets.QToolButton(self.pageOperasiPenjualan["widget"])
    self.pageOperasiPenjualan["buttonDelete"].setGeometry(QtCore.QRect(160, 320, 180, 32))
    self.pageOperasiPenjualan["buttonDelete"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageOperasiPenjualan["buttonDelete"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonDeleteData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageOperasiPenjualan["buttonDelete"].setIcon(icon)
    self.pageOperasiPenjualan["buttonDelete"].setIconSize(QtCore.QSize(174, 28))
    self.pageOperasiPenjualan["buttonDelete"].setAutoRaise(True)

    self.pageOperasiPenjualan["buttonBack"] = QtWidgets.QToolButton(self.pageOperasiPenjualan["widget"])
    self.pageOperasiPenjualan["buttonBack"].setGeometry(QtCore.QRect(204, 367, 95, 35))
    self.pageOperasiPenjualan["buttonBack"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageOperasiPenjualan["buttonBack"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonBack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageOperasiPenjualan["buttonBack"].setIcon(icon)
    self.pageOperasiPenjualan["buttonBack"].setIconSize(QtCore.QSize(97, 38))
    self.pageOperasiPenjualan["buttonBack"].setAutoRaise(True)
