from PyQt5 import QtCore, QtGui, QtWidgets

def pageManajemen(self) :
    self.pageManajemen = dict()
    self.pageManajemen["widget"] = QtWidgets.QWidget(self.centralwidget)
    self.pageManajemen["widget"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageManajemen["widget"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageManajemen["widget"].setMaximumSize(QtCore.QSize(500, 500))

    self.pageManajemen["Frame"] = QtWidgets.QLabel(self.pageManajemen["widget"])
    self.pageManajemen["Frame"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageManajemen["Frame"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageManajemen["Frame"].setMaximumSize(QtCore.QSize(500, 500))
    self.pageManajemen["Frame"].setText("")
    self.pageManajemen["Frame"].setPixmap(QtGui.QPixmap("Picture/FrameManajemen.jpg"))
    self.pageManajemen["Frame"].setScaledContents(True)

    self.pageManajemen["buttonPenjualan"] = QtWidgets.QToolButton(self.pageManajemen["widget"])
    self.pageManajemen["buttonPenjualan"].setGeometry(QtCore.QRect(160, 186, 180, 31))
    self.pageManajemen["buttonPenjualan"].setMinimumSize(QtCore.QSize(180, 31))
    self.pageManajemen["buttonPenjualan"].setMaximumSize(QtCore.QSize(180, 31))
    self.pageManajemen["buttonPenjualan"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageManajemen["buttonPenjualan"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonDataPenjualan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageManajemen["buttonPenjualan"].setIcon(icon)
    self.pageManajemen["buttonPenjualan"].setIconSize(QtCore.QSize(180, 31))
    self.pageManajemen["buttonPenjualan"].setAutoRaise(True)

    self.pageManajemen["buttonTerjual"] = QtWidgets.QToolButton(self.pageManajemen["widget"])
    self.pageManajemen["buttonTerjual"].setGeometry(QtCore.QRect(160, 249, 180, 31))
    self.pageManajemen["buttonTerjual"].setMinimumSize(QtCore.QSize(180, 31))
    self.pageManajemen["buttonTerjual"].setMaximumSize(QtCore.QSize(180, 31))
    self.pageManajemen["buttonTerjual"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageManajemen["buttonTerjual"].setText("")
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("Picture/buttonDataTerjual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageManajemen["buttonTerjual"].setIcon(icon)
    self.pageManajemen["buttonTerjual"].setIconSize(QtCore.QSize(180, 31))
    self.pageManajemen["buttonTerjual"].setAutoRaise(True)
