from PyQt5 import QtCore, QtGui, QtWidgets

def pageLihatDataTerjual(self) :
    self.pageLihatDataTerjual = dict()
    self.pageLihatDataTerjual["widget"] = QtWidgets.QWidget(self.centralwidget)
    self.pageLihatDataTerjual["widget"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageLihatDataTerjual["widget"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageLihatDataTerjual["widget"].setMaximumSize(QtCore.QSize(500, 500))

    self.pageLihatDataTerjual["Frame"] = QtWidgets.QLabel(self.pageLihatDataTerjual["widget"])
    self.pageLihatDataTerjual["Frame"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageLihatDataTerjual["Frame"].setText("")
    self.pageLihatDataTerjual["Frame"].setPixmap(QtGui.QPixmap("Picture/FrameLihatDataTerjual.jpg"))
    self.pageLihatDataTerjual["Frame"].setScaledContents(True)

    self.pageLihatDataTerjual["TabelData"] = QtWidgets.QTableWidget(self.pageLihatDataTerjual["widget"])
    self.pageLihatDataTerjual["TabelData"].setGeometry(QtCore.QRect(51, 101, 400, 271))
    self.pageLihatDataTerjual["TabelData"].setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
    self.pageLihatDataTerjual["TabelData"].setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    self.pageLihatDataTerjual["TabelData"].setAlternatingRowColors(True)
    self.pageLihatDataTerjual["TabelData"].setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    self.pageLihatDataTerjual["TabelData"].setRowCount(0)
    self.pageLihatDataTerjual["TabelData"].setColumnCount(4)
    item = QtWidgets.QTableWidgetItem()
    self.pageLihatDataTerjual["TabelData"].setHorizontalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem()
    self.pageLihatDataTerjual["TabelData"].setHorizontalHeaderItem(1, item)
    item = QtWidgets.QTableWidgetItem()
    self.pageLihatDataTerjual["TabelData"].setHorizontalHeaderItem(2, item)
    item = QtWidgets.QTableWidgetItem()
    self.pageLihatDataTerjual["TabelData"].setHorizontalHeaderItem(3, item)
    self.pageLihatDataTerjual["TabelData"].horizontalHeader().setDefaultSectionSize(88)
    self.pageLihatDataTerjual["TabelData"].horizontalHeader().setMinimumSectionSize(88)
    self.pageLihatDataTerjual["TabelData"].verticalHeader().setCascadingSectionResizes(True)
    self.pageLihatDataTerjual["TabelData"].verticalHeader().setDefaultSectionSize(20)
    self.pageLihatDataTerjual["TabelData"].verticalHeader().setMinimumSectionSize(20)

    self.pageLihatDataTerjual["buttonUnduh"] = QtWidgets.QToolButton(self.pageLihatDataTerjual["widget"])
    self.pageLihatDataTerjual["buttonUnduh"].setGeometry(QtCore.QRect(238, 380, 31, 31))
    self.pageLihatDataTerjual["buttonUnduh"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageLihatDataTerjual["buttonUnduh"].setText("")
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap("Picture/iconUnduh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageLihatDataTerjual["buttonUnduh"].setIcon(icon1)
    self.pageLihatDataTerjual["buttonUnduh"].setIconSize(QtCore.QSize(100, 100))
    self.pageLihatDataTerjual["buttonUnduh"].setAutoRaise(True)

    self.pageLihatDataTerjual["buttonBack"] = QtWidgets.QToolButton(self.pageLihatDataTerjual["widget"])
    self.pageLihatDataTerjual["buttonBack"].setGeometry(QtCore.QRect(37, 50, 31, 31))
    self.pageLihatDataTerjual["buttonBack"].setText("")
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap("Picture/iconPrevious .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageLihatDataTerjual["buttonBack"].setIcon(icon2)
    self.pageLihatDataTerjual["buttonBack"].setIconSize(QtCore.QSize(100, 30))
    self.pageLihatDataTerjual["buttonBack"].setAutoRaise(True)

    self.pageLihatDataTerjual["Teks"] = QtWidgets.QLabel(self.pageLihatDataTerjual["widget"])
    self.pageLihatDataTerjual["Teks"].setGeometry(QtCore.QRect(237, 410, 41, 16))

    self.pageLihatDataTerjual["labelInfo"] = QtWidgets.QLabel(self.pageLihatDataTerjual["widget"])
    self.pageLihatDataTerjual["labelInfo"].setGeometry(QtCore.QRect(76, 440, 351, 20))
    font = QtGui.QFont()
    font.setPointSize(10)
    self.pageLihatDataTerjual["labelInfo"].setFont(font)
    self.pageLihatDataTerjual["labelInfo"].setText("")
    self.pageLihatDataTerjual["labelInfo"].setAlignment(QtCore.Qt.AlignCenter)


    _translate = QtCore.QCoreApplication.translate
    item = self.pageLihatDataTerjual["TabelData"].horizontalHeaderItem(0)
    item.setText(_translate("MainWindow", "Kode Barang"))
    item = self.pageLihatDataTerjual["TabelData"].horizontalHeaderItem(1)
    item.setText(_translate("MainWindow", "Nama Barang"))
    item = self.pageLihatDataTerjual["TabelData"].horizontalHeaderItem(2)
    item.setText(_translate("MainWindow", "Jumlah Barang"))
    item = self.pageLihatDataTerjual["TabelData"].horizontalHeaderItem(3)
    item.setText(_translate("MainWindow", "Keterangan"))
    self.pageLihatDataTerjual["Teks"].setText(_translate("MainWindow", "UNDUH"))
