from PyQt5 import QtCore, QtGui, QtWidgets

def pageDeleteDataPenjualan(self) :
    self.pageDeleteDataPenjualan = dict()
    self.pageDeleteDataPenjualan["widget"] = QtWidgets.QWidget(self.centralwidget)
    self.pageDeleteDataPenjualan["widget"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageDeleteDataPenjualan["widget"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageDeleteDataPenjualan["widget"].setMaximumSize(QtCore.QSize(500, 500))

    self.pageDeleteDataPenjualan["Frame"] = QtWidgets.QLabel(self.pageDeleteDataPenjualan["widget"])
    self.pageDeleteDataPenjualan["Frame"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageDeleteDataPenjualan["Frame"].setText("")
    self.pageDeleteDataPenjualan["Frame"].setPixmap(QtGui.QPixmap("Picture/FrameDeleteDataPenjualan.jpg"))
    self.pageDeleteDataPenjualan["Frame"].setScaledContents(True)

    self.pageDeleteDataPenjualan["TabelData"] = QtWidgets.QTableWidget(self.pageDeleteDataPenjualan["widget"])
    self.pageDeleteDataPenjualan["TabelData"].setGeometry(QtCore.QRect(51, 101, 400, 271))
    self.pageDeleteDataPenjualan["TabelData"].setFrameShadow(QtWidgets.QFrame.Sunken)
    self.pageDeleteDataPenjualan["TabelData"].setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    self.pageDeleteDataPenjualan["TabelData"].setAlternatingRowColors(True)
    self.pageDeleteDataPenjualan["TabelData"].setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    self.pageDeleteDataPenjualan["TabelData"].setRowCount(10)
    self.pageDeleteDataPenjualan["TabelData"].setObjectName("TabelData")
    self.pageDeleteDataPenjualan["TabelData"].setColumnCount(4)
    item = QtWidgets.QTableWidgetItem()
    self.pageDeleteDataPenjualan["TabelData"].setHorizontalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem()
    self.pageDeleteDataPenjualan["TabelData"].setHorizontalHeaderItem(1, item)
    item = QtWidgets.QTableWidgetItem()
    self.pageDeleteDataPenjualan["TabelData"].setHorizontalHeaderItem(2, item)
    item = QtWidgets.QTableWidgetItem()
    self.pageDeleteDataPenjualan["TabelData"].setHorizontalHeaderItem(3, item)
    self.pageDeleteDataPenjualan["TabelData"].horizontalHeader().setDefaultSectionSize(88)
    self.pageDeleteDataPenjualan["TabelData"].horizontalHeader().setMinimumSectionSize(88)
    self.pageDeleteDataPenjualan["TabelData"].verticalHeader().setCascadingSectionResizes(True)
    self.pageDeleteDataPenjualan["TabelData"].verticalHeader().setDefaultSectionSize(20)
    self.pageDeleteDataPenjualan["TabelData"].verticalHeader().setMinimumSectionSize(20)

    self.pageDeleteDataPenjualan["buttonDelete"] = QtWidgets.QToolButton(self.pageDeleteDataPenjualan["widget"])
    self.pageDeleteDataPenjualan["buttonDelete"].setGeometry(QtCore.QRect(210, 384, 81, 31))
    self.pageDeleteDataPenjualan["buttonDelete"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageDeleteDataPenjualan["buttonDelete"].setText("")
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap("Picture/buttonDelete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageDeleteDataPenjualan["buttonDelete"].setIcon(icon1)
    self.pageDeleteDataPenjualan["buttonDelete"].setIconSize(QtCore.QSize(100, 100))
    self.pageDeleteDataPenjualan["buttonDelete"].setAutoRaise(True)

    self.pageDeleteDataPenjualan["buttonBack"] = QtWidgets.QToolButton(self.pageDeleteDataPenjualan["widget"])
    self.pageDeleteDataPenjualan["buttonBack"].setGeometry(QtCore.QRect(37, 50, 31, 31))
    self.pageDeleteDataPenjualan["buttonBack"].setText("")
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap("Picture/iconPrevious .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageDeleteDataPenjualan["buttonBack"].setIcon(icon2)
    self.pageDeleteDataPenjualan["buttonBack"].setIconSize(QtCore.QSize(100, 30))
    self.pageDeleteDataPenjualan["buttonBack"].setAutoRaise(True)

    self.pageDeleteDataPenjualan["labelInfo"] = QtWidgets.QLabel(self.pageDeleteDataPenjualan["widget"])
    self.pageDeleteDataPenjualan["labelInfo"].setGeometry(QtCore.QRect(66, 429, 367, 31))
    font = QtGui.QFont()
    font.setPointSize(10)
    self.pageDeleteDataPenjualan["labelInfo"].setFont(font)
    self.pageDeleteDataPenjualan["labelInfo"].setText("")
    self.pageDeleteDataPenjualan["labelInfo"].setAlignment(QtCore.Qt.AlignCenter)


    _translate = QtCore.QCoreApplication.translate
    item = self.pageDeleteDataPenjualan["TabelData"].horizontalHeaderItem(0)
    item.setText(_translate("MainWindow", "Kode Barang"))
    item = self.pageDeleteDataPenjualan["TabelData"].horizontalHeaderItem(1)
    item.setText(_translate("MainWindow", "Nama Barang"))
    item = self.pageDeleteDataPenjualan["TabelData"].horizontalHeaderItem(2)
    item.setText(_translate("MainWindow", "Jumlah Barang"))
    item = self.pageDeleteDataPenjualan["TabelData"].horizontalHeaderItem(3)
    item.setText(_translate("MainWindow", "Keterangan"))

