from PyQt5 import QtCore, QtGui, QtWidgets

def pageInputDataTerjual(self) :
    self.pageInputDataTerjual = dict()
    self.pageInputDataTerjual["widget"] = QtWidgets.QWidget(self.centralwidget)
    self.pageInputDataTerjual["widget"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageInputDataTerjual["widget"].setMinimumSize(QtCore.QSize(500, 500))
    self.pageInputDataTerjual["widget"].setMaximumSize(QtCore.QSize(500, 500))

    self.pageInputDataTerjual["Frame"] = QtWidgets.QLabel(self.pageInputDataTerjual["widget"])
    self.pageInputDataTerjual["Frame"].setGeometry(QtCore.QRect(0, 0, 500, 500))
    self.pageInputDataTerjual["Frame"].setText("")
    self.pageInputDataTerjual["Frame"].setPixmap(QtGui.QPixmap("Picture/FrameInputDataTerjual.jpg"))
    self.pageInputDataTerjual["Frame"].setScaledContents(True)

    self.pageInputDataTerjual["inputJumlah"] = QtWidgets.QLineEdit(self.pageInputDataTerjual["widget"])
    self.pageInputDataTerjual["inputJumlah"].setGeometry(QtCore.QRect(56, 272, 384, 26))
    font = QtGui.QFont()
    font.setPointSize(12)
    self.pageInputDataTerjual["inputJumlah"].setFont(font)
    self.pageInputDataTerjual["inputJumlah"].setMaxLength(50)
    self.pageInputDataTerjual["inputJumlah"].setFrame(False)
    self.pageInputDataTerjual["inputJumlah"].setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)

    self.pageInputDataTerjual["buttonInput"] = QtWidgets.QToolButton(self.pageInputDataTerjual["widget"])
    self.pageInputDataTerjual["buttonInput"].setGeometry(QtCore.QRect(209, 390, 84, 34))
    self.pageInputDataTerjual["buttonInput"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageInputDataTerjual["buttonInput"].setText("")
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap("Picture/buttonInput.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageInputDataTerjual["buttonInput"].setIcon(icon1)
    self.pageInputDataTerjual["buttonInput"].setIconSize(QtCore.QSize(80, 30))
    self.pageInputDataTerjual["buttonInput"].setAutoRaise(True)

    self.pageInputDataTerjual["inputNama"] = QtWidgets.QLabel(self.pageInputDataTerjual["widget"])
    self.pageInputDataTerjual["inputNama"].setGeometry(QtCore.QRect(56, 208, 380, 21))
    self.pageInputDataTerjual["inputNama"].setText("")
    font = QtGui.QFont()
    font.setPointSize(12)
    self.pageInputDataTerjual["inputNama"].setFont(font)

    self.pageInputDataTerjual["inputKode"] = QtWidgets.QComboBox(self.pageInputDataTerjual["widget"])
    self.pageInputDataTerjual["inputKode"].setGeometry(QtCore.QRect(58, 140, 380, 26))
    self.pageInputDataTerjual["inputKode"].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.pageInputDataTerjual["inputKode"].setFrame(False)
    self.pageInputDataTerjual["inputKode"].addItem("")
    self.pageInputDataTerjual["inputKode"].setItemText(0, "")
    font = QtGui.QFont()
    font.setPointSize(12)
    self.pageInputDataTerjual["inputKode"].setFont(font)

    self.pageInputDataTerjual["buttonBack"] = QtWidgets.QToolButton(self.pageInputDataTerjual["widget"])
    self.pageInputDataTerjual["buttonBack"].setGeometry(QtCore.QRect(36, 44, 30, 31))
    self.pageInputDataTerjual["buttonBack"].setText("")
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap("Picture/iconPrevious .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.pageInputDataTerjual["buttonBack"].setIcon(icon2)
    self.pageInputDataTerjual["buttonBack"].setIconSize(QtCore.QSize(100, 30))
    self.pageInputDataTerjual["buttonBack"].setAutoRaise(True)

    self.pageInputDataTerjual["inputKeterangan"] = QtWidgets.QLineEdit(self.pageInputDataTerjual["widget"])
    self.pageInputDataTerjual["inputKeterangan"].setGeometry(QtCore.QRect(56, 340, 384, 26))
    font = QtGui.QFont()
    font.setPointSize(12)
    self.pageInputDataTerjual["inputKeterangan"].setFont(font)
    self.pageInputDataTerjual["inputKeterangan"].setMaxLength(50)
    self.pageInputDataTerjual["inputKeterangan"].setFrame(False)
    self.pageInputDataTerjual["inputKeterangan"].setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)

    self.pageInputDataTerjual["infoInput"] = QtWidgets.QLabel(self.pageInputDataTerjual["widget"])
    self.pageInputDataTerjual["infoInput"].setGeometry(QtCore.QRect(60, 431, 380, 24))
    font = QtGui.QFont()
    font.setPointSize(10)
    self.pageInputDataTerjual["infoInput"].setFont(font)
    self.pageInputDataTerjual["infoInput"].setText("")
    self.pageInputDataTerjual["infoInput"].setAlignment(QtCore.Qt.AlignCenter)
